#!/usr/bin/php -q
<?php

  #ini_set("error_reporting","E_ALL");
  
  function getMojo( $path = '.', $level = 0 )
  {
    $mojo ="";
    //if you have your mojo lib in a diff set of libs set them here
    $scan = array( 'lib','vendor','mojo', 'src', 'Mojo.class.php' );
    $dh = @opendir( $path );
    while( false !== ( $file = @readdir( $dh ) ) ){
        if( in_array( $file, $scan ) ){
            if( is_dir( "$path/$file" ) ){
                return getMojo( "$path/$file", ($level+1) );
            } else {
                if($file == 'Mojo.class.php'){
                    $mojo = $path.'/'.$file;
                    return $mojo;
                }
            }
        }
    }
    @closedir( $dh );
    return $mojo;
  }
  
  array_shift($argv);  $cmd = "";
  foreach($argv as $v) $cmd .= " ".$v;
  passthru(getMojo('.').$cmd);

?>
